version: '3'

services:
  sql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

